FPS = 60
RESOLUTION = WIDTH, HEIGHT = 900, 990
DISTANCE_FACTOR = 10

SPRITE_SIZE = 45


# PLAYER INITIAL POSITION
PLAYER_POSITION = PLAYER_X, PLAYER_Y = 15, 18

# GHOSTS INITIAL POSITIONS
BLINKY_POSITION = BLINKY_X, BLINKY_Y = 3, 2
PINKY_POSITION = PINKY_X, PINKY_Y = 3, 2
INKY_POSITION = INKY_X, INKY_Y = 14, 15
CLYDE_POSITION = CLYDE_X, CLYDE_Y = 15, 15


